### ISSUE TITLE
Types 

### ISSUE THREAD

**Issue by Tjerk-Haaye-Henricus** [imgproxy/imgproxy-node#1]
Hey there, 

maybe a dumb question but how can i use the types :D :D

**Comment by NickClark** [comment]
Yeah, the types don't work for me either.

I see the following error in the editor:

```
Could not find a declaration file for module '@imgproxy/imgproxy-node'. '/Users/**/node_modules/.pnpm/@imgproxy+imgproxy-node@1.0.2/node_modules/@imgproxy/imgproxy-node/dist/esm/index.js' implicitly has an 'any' type.
  There are types at '/Users/**/node_modules/@imgproxy/imgproxy-node/dist/imgproxy-node.d.ts', but this result could not be resolved when respecting package.json "exports". The '@imgproxy/imgproxy-node' library may need to update its package.json or typings.ts(7016)
```

Is this actually working for anyone? I'm surprised this isn't getting more attention.

**Comment by artzaitsev** [comment]
Can you update the library in npm registry? The commit hadn't been updated [there](https://www.npmjs.com/package/@imgproxy/imgproxy-node/v/1.0.2?activeTab=code)

**Comment by Alqanar** [comment]
Thank you @artzaitsev. I was overwhelmed and it slipped my mind.
New version is published.
