### ISSUE TITLE
URL safe encoding

### ISSUE THREAD

**Issue by PrivateGER** [imgproxy/imgproxy-node#4]
This package does NOT do URL safe encoding if you aren't using encrypted URLs, which is the path handling them properly.

See this line: https://github.com/imgproxy/imgproxy-node/blob/c25919cb7866c967a30614a8a23fb7de0c89a61c/src/utils/normalizeUrl.ts#L20
It does a plain btoa without any further processing happening later.

**Comment by PrivateGER** [comment]
Can be fixed like this:
https://github.com/PrivateGER/imgproxy-node/blob/main/src/utils/normalizeUrl.ts#L20

This is using the same encoding used in the encrypted URLs.

**Comment by Alqanar** [comment]
Thank you for your issue.
I added changes.
